### ISSUE TITLE
Make core.application.OpalApplication.get_menu_items safer

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1101]
At the moment `OpalApplication.get_menu_items` returns a reference the `OpalApplication.menu_items` property.

We've seen a couple of occurrences of people appending things to that array.

This means that every time `get_menu_items` it updates the list in place, and gradually makes the menu longer and longer. We should make sure that the default implementation doesn't make this easy to do - probably by returning a copy of the original list in some form :)

## Reproducing the issue

```
opal startproject testing
```
Then in `testing/__init__.py` override `get_menu_items`:
```python
from opal.core import menus

class Application(application.OpalApplication):
   #
   # ... other stuff ...
   #

    @classmethod
    def get_menu_items(klass, user=None):
        items = application.OpalApplication.get_menu_items(user=user)
        items.append(
            menus.MenuItem(
                href="/some-url/",
                icon="fa-thumbs-down", 
                display="Once was enough",
                index=-1
            ))
        return items
```
Then refresh the page several times.

## Fixing the issue

Tests should go in opal/tests/test_core_application.py

**Comment by davidmiller** [comment]
@fredkingham Actually I think this might already be fixed in 0.8.2 - we moved the menuitems for logut / admin there and out of the template...
