### ISSUE TITLE
add equality to the menu items

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1148]
add an __eq__ method to the MenuItem cls

**Comment by pdmorrow** [comment]
Hi Fred,

Would ebf2594 work for you?  This is testing object equality rather than "visual" equality (which I think would just be matching display_name and icon).  If ebf2594 looks sensible I'll send it for a PR tomorrow.

Cheers,
Peter.

**Comment by fredkingham** [comment]
I think it looks great, I think there's an argument that some attributes such as index don't need to be part of equality, but I'm not sure if that's right or not!

I think we should go with this, looks great, pull request please! 👍

**Comment by pdmorrow** [comment]
Cool.  Was thinking the same re: index/others fields.  PR on the way.
