### ISSUE TITLE
hard code 'Mine' into the Tagging.build_field_schema

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1153]
at the moment Mine isn't appearing.

This can be checked by trying to add the mine tag in the user interface. If after you save it. The tag appears in the side bar and as a tag when you use the edit teams modal. Then this has worked.

**Comment by fredkingham** [comment]
further information here

https://github.com/openhealthcare/elcid/issues/1373

**Comment by davidmiller** [comment]
I think we should stop special casing the mine list at all ! It's an application level feature...
