### ISSUE TITLE
Pluralss of model itemss

### ISSUE THREAD

**Issue by awilkins** [openhealthcare/opal#1192]
![image](https://user-images.githubusercontent.com/368399/28239229-02eb82ba-695f-11e7-8365-c50bd0ed413b.png)

**Comment by davidmiller** [comment]
Many of our default models do not set their admin verbose_name_plural values sensibly.

### Steps to reproduce

Create a new app with `opal startproject foo` 
Navigate to the admin
Read things which are not proper Englishes

### Acceptance criteria

- [ ] Set appropriate Meta.verbose_name_plural properties
- [ ] Note in the changelog
