### ISSUE TITLE
Confusion with the pip versions

### ISSUE THREAD

**Issue by voidspacexyz** [openhealthcare/opal#1272]
I did a pip install opal

Here is the confusion I have : 
When I do 
$ opal --version
Opal 0.9.0

But the pip version says a different version
$ pip freeze --user | grep opal
opal==0.8.3

**Comment by fredkingham** [comment]
hi!
 I can see how there could be some confusion. If you run 'which opal' does it point to the opal in your virtualenv?

**Comment by voidspacexyz** [comment]
Okie, I made a mistake in my issue.
I did a pip install --user opal , so opal is installed my local user directory

$ which opal
/home/ram/.local/bin/opal

**Comment by davidmiller** [comment]
I think we can consider this closed now ? 

Do shout if you have further issues @voidspacexyz
