### ISSUE TITLE
./manage.py load_lookup_lists doesn't load from separate lists

### ISSUE THREAD

**Issue by JMathiszig-Lee** [openhealthcare/opal#1275]
Load lookup lists detects separate .json files and loads lookuplist name but not the data from within. 
I initally thought this was due to not having the properly formatted name but this did not correct the problem when formatted correct and same JSON pasted into main lookuplists.json works correctly.

Link to lookup lists in question [https://github.com/anaesthetic-health-chart/anaesthetic/tree/preop/anaesthetic/data/lookuplists](url)

**Comment by davidmiller** [comment]
The way this command works, it looks in all installed Django apps for ./data/lookuplists.json or ./data/`$api_name`.json by default.

You can however pass in the --file argument and specify a file to load. e.g. `python manage.py load_lookup_lists --file $your_file` 

The documentation for these could definitely use some love - we'll fix that as part of #1216 

Closing this for now...
