### ISSUE TITLE
When I delete a lookup list I do not want it to delete all related models

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1281]
We need to make sure when we delete a lookup list object it does not delete

https://github.com/openhealthcare/opal/blob/v0.9.0/opal/core/fields.py#L68

should be changed to 

fk_kwargs = dict(blank=True, null=True, on_delete=models.SET_NULL

this will create migrations.

We should also override the delete method (and potentially the delete on the queryset) to update the ft value with the old value of the fk on save.

**Comment by davidmiller** [comment]
Done in [this commit](https://github.com/openhealthcare/opal/commit/fa645701d52d18866d2dd12b3817a159271c3769) - closing.
