### ISSUE TITLE
Can we add a method that provides the latest open episode?

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1299]

**Comment by davidmiller** [comment]
You mean e.g. `Patient.episode_set.filter(active=True).order_by('start')[0]` ?

**Comment by fredkingham** [comment]
I think I wanted one on the client side as we seem to do iterate over all episodes and get the active one a few different times.

**Comment by davidmiller** [comment]
Right. So I think that was originally the idea behind `get_active_episode` / `active_episode_id` ?

e.g. `Patient.get_active_episode()` is :
```python
    def get_active_episode(self):
        for episode in self.episode_set.order_by('id').reverse():
            if episode.active:
                return episode
        return None
```
and then `Patient.to_dict` includes:
```python
'active_episode_id': active_episode.id if self.get_active_episode() else None
```

In practice I think it's probably more complicated - I suspect this is from before we really catered for multiple overlapping active episodes or episode categories.

It kind of works for the 'default' case where you assume an episode to be an inpatient admission - that's more or less what [hospital_number.js](https://github.com/openhealthcare/opal/blob/49601932a609df289a38faa063be3a2d4662d2aa/opal/static/js/opal/controllers/hospital_number.js) does... but honestly we might want to revisit that entirely and remove/rename active_episode[_id].

Where are iterating through all episodes on the client?

**Comment by fredkingham** [comment]
I thought we were doing it, but I can't actually now find any instance. I'm going to close this.
