### ISSUE TITLE
Add pathways to the karma defaults

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1300]
Karma is the javascript test runner that Opal uses.

Opal has lots of javascript dependencies (doesn't everyone?)

As Opal is super modular, with lots of different plugins and applications. Every time we update a javascript dependency, we don't want to have to update all of them.

So... Opal gives us intelligent [karma defaults](https://github.com/openhealthcare/opal/blob/v0.9.1/opal/tests/js_config/karma_defaults.js) so we don't need to update all libraries javascript dependencies whenever we update a library.

These karma defaults do not include pathways! We want to be able to test apps that use pathways, so add to karma config dependencies.

- [ ] add a glob of all pathway dependencies to OPAL_DEPENDENCIES to [karma defaults](https://github.com/openhealthcare/opal/blob/v0.9.1/opal/tests/js_config/karma_defaults.js) 
- [ ] remove the line in the RFH that manually adds in pathways
- [ ] everything should still pass

**Comment by davidmiller** [comment]
> remove the line in the RFH that manually adds in pathways
@fredkingham which line is that  ?

**Comment by fredkingham** [comment]
sorry, I was wrong, not RFH, UCH

https://github.com/openhealthcare/elcid/blob/v0.7.0/config/karma.conf.js
