### ISSUE TITLE
models with fk_or_ft fields should not be deleted when we delete a lookup list

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1326]
if we have a DogOwner with and fk_ft field to Dog.

When we delete the Dog with the name 'Spot', the ft field on DogOwner should be updated to Spot

**Comment by davidmiller** [comment]
This is dealt with in https://github.com/openhealthcare/opal/commit/fa645701d52d18866d2dd12b3817a159271c3769
