### ISSUE TITLE
Investigation form has fields which don't exist on the model

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1328]
We have fields in the form that do not exist in the model. Suggestion would be to remove the model.

https://github.com/openhealthcare/opal/blob/v0.9.1/opal/templates/forms/investigation_form.html#L549-L554

thoughts @davidmiller?

**Comment by davidmiller** [comment]
Vanilla new app needs a way to do simplistic tests and results - if it's broken we need to fix it...

**Comment by davidmiller** [comment]
I think we're just taking this out in the end. Closing.
