### ISSUE TITLE
documentation for episode categories tweaks

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/opal#1358]
* the current [documentation page](http://opal.openhealthcare.org.uk/docs/v0.9.1/reference/episode_categories/) could do with an example, to show good practice and to clarify what filename the episode categories should be placed in (episode_category.py not episodes.py)

* [documentation page for Episodes](http://opal.openhealthcare.org.uk/docs/v0.9.1/reference/episode/
) mentions Episode Category but it would be nice if it linked to the EpisodeCategory documentation, just to help with navigation and clarity

**Comment by davidmiller** [comment]
Closing this as addressed in #1374
