### ISSUE TITLE
Get the testsuite working under Windows

### ISSUE THREAD

**Issue by lamby** [openhealthcare/opal#1360]
See, for example, #1297.

**Comment by lamby** [comment]
https://www.appveyor.com/

**Comment by lamby** [comment]
Filed: https://github.com/davidmiller/ffs/pull/13

**Comment by lamby** [comment]
Filed: https://github.com/davidmiller/ffs/pull/14 — _Initial support for Windows, at least allowing module import_

**Comment by lamby** [comment]
Filed: https://github.com/openhealthcare/opal/pull/1363 — _Add ghetto --failfast support to runtests.py_

**Comment by lamby** [comment]
Filed https://github.com/davidmiller/ffs/pull/17 — _ffs.path: Correct tread -> treat typo_

**Comment by lamby** [comment]
Filed https://github.com/davidmiller/ffs/pull/18 — _ffs.nix: Explicitly pass str instances not Path to shutil methods_

**Comment by lamby** [comment]
Filed https://github.com/davidmiller/ffs/pull/19 — _Pass a genuine str instance to os.path.abspath, not our wrapper_

**Comment by lamby** [comment]
![](https://i.imgur.com/ymtE0z1.jpg)

@davidmiller #1366 will make the testsuite work on Windows, given a recent enough ffs (ie. with my recent PRs merged, released and requirements.txt updated to match)

I've split off #1365 so that we can close this particular issue.

**Comment by lamby** [comment]
@davidmiller Can you release a new ffs at let me know the version? :)

**Comment by davidmiller** [comment]
Released and a version bump PR for you ^^

**Comment by lamby** [comment]
:+1:

**Comment by lamby** [comment]
Blocking on https://github.com/openhealthcare/opal/pull/1367#pullrequestreview-88964840

**Comment by lamby** [comment]
Appveyor tests #1365 (passing!) are now also on this branch :)

**Comment by lamby** [comment]
(ACK that tests are failing. Will look into soon.)

**Comment by davidmiller** [comment]
(OPINION that the errors coming out of *nix are significantly more helpful due to providing 'context' and/or 'details')

Also: I didn't know `django.core.management.call_command` was a thing.
It seems ++better than subprocess presuming it can be made to work.

**Comment by lamby** [comment]
Sure, I'm not stuck, just acknowledging they are failing..

**Comment by davidmiller** [comment]
Closing this as we've been running on Appveyor for quite some time now...

**Comment by lamby** [comment]
:+1:
