### ISSUE TITLE
Ensure that you can use the commandline tool in windows

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#1361]
We should be able to run the four common `opal` commands on Windows - check that these work.

- [x] startproject
- [x] startplugin
- [x] scaffold
- [x] test

(Blocked by #1360)

Commands documentation: 
http://opal.openhealthcare.org.uk/docs/v0.9.0/guides/command_line_tool/

**Comment by lamby** [comment]
``startproject`` works

**Comment by lamby** [comment]
As in, ``startproject`` *now* works  :)

**Comment by lamby** [comment]
These all work now, so closing issue. The code for them is on #1360 etc.

**Comment by lamby** [comment]
@davidmiller On my windows, pip installs this script to ``C:\Python\Scripts\opal`` (or close enough!) that DTRT. This seems to be The Windows Way of doing it.

**Comment by davidmiller** [comment]
On mine too although that script doesn't seem to be editable...

e.g. when I run the script from powershell, it opens the file in notepad instead of running it... I guess my immediate question is what are we doing differently?
![screen shot 2018-01-25 at 14 01 42](https://user-images.githubusercontent.com/17229/35392164-e7a8c694-01d8-11e8-9989-d07ada1ad518.png)

**Comment by lamby** [comment]
``C:\Python27\python.exe bin/opal startproject`` :)

**Comment by davidmiller** [comment]
Ah, I see...

I think that's much less good than converting `scripts` to `entry_points` which creates an `opal.exe` so that inside a virtualenv you can type e.g. :
`opal startproject` 

Our documentation is going to be much less confusing for all concerned that way :) 

To learn this I had to do the work - stacked branch is [here](https://github.com/openhealthcare/opal/commit/d997fb8af5198ef9e4657faf51f70ebf8322f3ff) - TBH we can merge that after PR #1385

**Comment by davidmiller** [comment]
Definitely seen this working now - closing.

**Comment by lamby** [comment]
:+
