### ISSUE TITLE
bug in Opal reverse url lookups which use dotted Python paths

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/opal#1379]
This is due to a deprecated API in Django 1.10

Specifically this means things like `<a href="{% url 'django.contrib.auth.views.logout' %}" title="Log out">` will error.

The fix is to change to `<a href="{% url 'logout' %}" title="Log out">`

and add a name to that path:

```
    url(r'^accounts/logout/$',
        logout, {'next_page': '/'},
        name='logout'),
```

Plus there should be a test in opal/test-urls.py that checks this reverse lookup

**Comment by davidmiller** [comment]
Fixed in https://github.com/openhealthcare/opal/pull/1380
