### ISSUE TITLE
Pathway error

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1396]
<img width="841" alt="screen shot 2018-02-01 at 10 32 10" src="https://user-images.githubusercontent.com/2175455/35674068-63b117f2-073b-11e8-8405-9275682eb001.png">

**Comment by davidmiller** [comment]
Is this still a thing? Do we have a reproduction case yet ?

**Comment by fredkingham** [comment]
This has not been repeated, closing this for the time being.
