### ISSUE TITLE
How long can we go on like this? (Let's add a duration field)

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1403]
In django 1.8 there is a [duration field](https://docs.djangoproject.com/en/1.11/ref/models/fields/#durationfield)

This would be super useful for, for example tracking symptom duration.

Django accepts 3 different types of timedelta structure
https://github.com/django/django/blob/master/django/utils/dateparse.py#L124

I think my preferred option is https://en.wikipedia.org/wiki/ISO_8601#Durations

We would need:
- [ ] some sort of form field(s)
preferred default would be an input for years, an input for months and an input for days.

- [ ] a directive that wraps these and puts them in an ISO_8601 structure.

- [ ] an update from dict that handles this by giving them straight to the dateparse function above.

- [ ] scaffolding change to use the above

- [ ] some way of having a search widget
(answers on a post card, I have no idea how to make this look nice)

**Comment by davidmiller** [comment]
@fredkingham How much do you want this... I can see it in theory, but not sure I'd personally prioritise it soon ?

**Comment by fredkingham** [comment]
I would like it, but definitely not one for now.
