### ISSUE TITLE
add a growl notification opetion to the open-pathway directive

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1411]
After I do a modal-pathway with the open-pathway directive I want a growl notification for success and maybe one for failure.

e.g. if I do remove from list, I want a growl notification 'this-patient-has-been-removed-from-list'

**Comment by davidmiller** [comment]
I think less baking in Growl for now...
Lifecycle hooks for Pathway, sure, but it's a much bigger question
