### ISSUE TITLE
default Opal `{% date_of_birth_field %}` does not use a date picker

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/opal#1430]
Is there a reason that `date_of_birth_field.html` doesn't utilise a date picker, as per `datepicker.html`, or is it just something that we haven't got around to updating?

Is there any special additional functionality we're getting from `date_of_birth_field.html`?

Could `date_of_birth_field.html` simply include a `datepicker.html` in its code?

Or is it better to just use a plain `datepicker`

**Comment by davidmiller** [comment]
Most people's dates of birth are not in the last month.

Navigating to 1975 in a datepicker is unpleasant and less good than typing in 1975.

The date of birth field gives you date validation for a specific date format but the speed of typing the date.

It can of course be trivially swapped out by any given form for a datepicker if the application developer wants to :)

**Comment by fredkingham** [comment]
@pacharanero 
everything @davidmiller  says.

Also we do get additional validation around the date of birth. You can't add a date in the future or one over 150 years ago.

**Comment by fredkingham** [comment]
I think we're ok with the dob justification so I'm closing this
