### ISSUE TITLE
Patient List Groups in the PatientList switcher

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#1457]
Where we're using `TabbedPatientListGroup` we may well not want each member in the list switcher.

- [ ] Add a property to `opal.core.patient_lists.TabbedPatientListGroup` which promises that, if True, member lists will be removed from the list switcher 
- [ ] Add an `is_valid` check to ensure that if this property is True, we can `get_slug` and that there is a display name
- [ ] Update `opal.views.PatientListTemplateView.get_context_data` such that it does not include lists which are members of a group where this property is True in the `'lists'` variable
- [ ] Consider refactoring this logic out of the view and into `opal.core.patient_lists` as a function 
- [ ] Tests
- [ ] Documentation

This ticket unblocks openhealthcare/elcid#1509

**Comment by pacharanero** [comment]
I've been looking further at this following call/pairing with @davidmiller 

I think the proposed implementation will work adequately, and will implement it as such, but it feels a bit clunky to be using `display_member_lists_in_list_switcher = False` exclued ALL the members from the Patient ListSwitcher, without any granularity.

I was wondering if an eventual API with more flexibility and clarity would be something like this:

```python
member_lists = [
    (WalkinNurseTriage, list_switcher_item=False),
    (WalkinDoctor, list_switcher_item=False),
    (WalkinReview, list_switcher_item=False),
]
display_name = "Walkin" # optional
```

this gives complete flexibility as to which PatientLists are shown in the ListSwitcher, ranging from just `display_name` on its own, all the way up to any combination of the members.

**Comment by pacharanero** [comment]
some initial WIP on this branch: https://github.com/openhealthcare/opal/tree/1457-patient-list-groups-in-the-patientlist-switcher

**Comment by pacharanero** [comment]
There is also some code in elcid-uch which facilitates testing/development of this feature. It is in branch https://github.com/openhealthcare/elcid/tree/1509-given-tabbed-navigation-can-we-make-all-of-opat-one-option-on-teams-dropdown

**Comment by pacharanero** [comment]
Removing the `PatientList` objects from the `list_items` list using a list comprehension and finding them by `display_name` feels really hacky. Is there a better way I'm not seeing?

https://github.com/openhealthcare/opal/blob/fefcea26336a20aa15766e46297b9573da1a782f/opal/views.py#L71-L76

**Comment by davidmiller** [comment]
You need access to the current list group from that method I think.
If you pass it in as a kwarg to the method, then you can check for membership rather than hardcoding display names:
```[n for n in a if n not in y]```

**Comment by pacharanero** [comment]
Thanks @davidmiller this is kind of what I was aiming for. (The hardcoded display names were only just to test it worked). I'll have a look at it later in the week if I have time.

**Comment by pacharanero** [comment]
From the discussion on the call and on Slack this morning, it doesn't yet feel as though we have agreement yet on how this feature should be implemented. @fredkingham would you append your thoughts here?

**Comment by davidmiller** [comment]
Now profoundly unlikely to do this - have strongly reconsidered the idea that this is a general case !
