### ISSUE TITLE
One spreadsheet list to rule them all

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1477]
We have 2 spreadsheet lists.

https://github.com/openhealthcare/opal/blob/v0.10.0/opal/templates/patient_lists/spreadsheet_list.html
and
https://github.com/openhealthcare/opal/blob/v0.10.0/opal/templates/patient_lists/layouts/spreadsheet_list.html

we would like 1.

Ideally this will have 
- [x] will be the layouts/spreadsheet_list.html (ie we should be able to delete the other one)
- [x] the episode actions block that @pacharanero put into v0.10.0
- [x] make sure we don't lose anything, i.e blocks (inc the episode_actions block introduced by @pacharanero )
- [x] change the patient lists to default to the layouts
- [x] update the change log to state this change

**Comment by pacharanero** [comment]
I did notice that there is a spreadsheet_list.html in

`opal/templates/patient_lists/spreadsheet_list.html`

and also one in

`opal/templates/patient_lists/layouts/spreadsheet_list.html`

presumably we only want one

**Comment by davidmiller** [comment]
>  change the patient lists to default to the layouts
What does this mean ? 

> or the user of patails 
Typo?

**Comment by pacharanero** [comment]
>> change the patient lists to default to the layouts

> What does this mean ?

I think it means to use 'opal/templates/patient_lists/*layouts*/spreadsheet_list.html' as opposed to 'opal/templates/patient_lists/spreadsheet_list.html'.

>> or the user of patails

> Typo?

I think so, it looks like a portmanteau of *pat*ient and det*ails* ;-)

**Comment by pacharanero** [comment]
Having looked at the various files a couple of weeks ago and again today, I'm very wary of breaking something with this ticket, and wonder if this might be best done as a pairing exercise?

It's a little complex when you start looking at it. For example:

opal/templates/patient_lists/layouts/spreadsheet_list.html `extends` opal/templates/patient_lists/layouts/spreadsheet_list_base.html

whereas

opal/templates/patient_lists/spreadsheet_list.html `extends`
opal/templates/layouts/left_panel.html

opal/templates/layouts/left_panel.html and opal/templates/patient_lists/layouts/spreadsheet_list_base.html are _very_ different files.

So we have to check both ways that we are not losing anything needed, adding anything we shouldn't be, or inadvertently overriding stuff and creating UI havoc generally. Much of the stuff in those files I am unfamiliar with and would not be sure what to keep, what to change etc

**Comment by davidmiller** [comment]
Suggested Plan:

- [ ] Update ./templates/patient_lists/spreadsheet_list.html to use the dropdown_menu partial. 
- [ ] Take the layout elements from ./layouts/left_panel.html and put them directly in the file (remove the extends) 
- [ ] `mv ./templates/patient_lists/spreadsheet_list.html ./templates/patient_lists/spreadsheet_list_base.html`
- [ ] Update `opal.core.patient_lists.PatientList` to use a template that still exists
- [ ] Review in browser on a version of elCID UCH (clicking about and run `/stories/` ) 
- [ ] Take a look at the base template and add any `{% block ` definitions of things that people are likely to want to override
- [ ] Changelog
- [ ] Update reference documentation to only talk about templates that exist
