### ISSUE TITLE
patient.to_dict, episode.to_dict and episode queryset to_dict should take subrecords

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1490]
At the moment we serialise all of the subrecords. 

Change this so that they take in a list of subrecords, if a list is not supplied they should serialise everything.

An implementation probably looks something similar to
https://github.com/openhealthcare/elcid-rfh/blob/v0.3.0/elcid/patient_lists.py#L110

**Comment by davidmiller** [comment]
I think the reason you want this is speed and the potential to limit things on patient lists?

This would worry me TBH...

I can very much see this breaking front end forms/controllers/actions...

What even is a javascript `new Episode()` or `new Patient()` if we do this? 

I suggest having a design conversation that thinks about serialization in general. 

You'd want to include this ticket, the stuff about delegating it to managers from #1493 consider DRF as per #1001 

Honestly, I can imagine that what we really want here is something more like a lightweight PEP than an isssue...

**Comment by fredkingham** [comment]
I mean these are great points. 

It could be that pagination is more of an answer.

I also wanted it so that we could pass through the subrecords to the Episode serialiser so that we don't duplicate patient subrecord serialisation when we serialise patients, but maybe there's another solution to this as well.
