### ISSUE TITLE
FileNotFound error when executing opal startproject myapp

### ISSUE THREAD

**Issue by dumodem** [openhealthcare/opal#1497]
C:\Users\User>opal startproject mynewapp
Bootstrapping your Opal project...
Creating project dir at C:\Users\User\mynewapp
Creating Database
Calling: python mynewapp\manage.py makemigrations mynewapp --traceback
Migrations for 'mynewapp':
  mynewapp\mynewapp\migrations\0001_initial.py:
    - Create model Allergies
    - Create model Demographics
    - Create model Diagnosis
    - Create model Investigation
    - Create model Location
    - Create model PastMedicalHistory
    - Create model PatientConsultation
    - Create model SymptomComplex
    - Create model Treatment
Calling: python mynewapp\manage.py migrate --traceback
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, contenttypes, mynewapp, op
al, reversion, sessions, sites
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying axes.0001_initial... OK
  Applying axes.0002_auto_20151217_2044... OK
  Applying axes.0003_auto_20160322_0929... OK
  Applying opal.0001_initial... OK
  Applying opal.0002_auto_20150822_0820... OK
  Applying opal.0003_speciality... OK
  Applying opal.0003_auto_20150922_1825... OK
  Applying opal.0004_merge... OK
  Applying opal.0005_team_visibile_in_list... OK
  Applying opal.0006_auto_20151109_1232... OK
  Applying opal.0007_tagging_archived... OK
  Applying opal.0008_auto_20151216_1803... OK
  Applying opal.0009_glossolaliasubscription... OK
  Applying opal.0010_auto_20160229_1211... OK
  Applying opal.0011_patientrecordaccess... OK
  Applying opal.0012_maritalstatus_title... OK
  Applying opal.0013_inpatientadmission... OK
  Applying opal.0014_auto_20160330_0952... OK
  Applying opal.0015_auto_20160330_0955... OK
  Applying opal.0016_tagging_value... OK
  Applying opal.0017_auto_20160509_1645... OK
  Applying opal.0018_auto_20160603_0934... OK
  Applying opal.0019_auto_20160607_1039... OK
  Applying opal.0020_referralorganisation_referralreason... OK
  Applying opal.0021_patientconsultationreasonforinteraction... OK
  Applying opal.0022_episode_stage... OK
  Applying opal.0023_auto_20160630_1340... OK
  Applying opal.0024_auto_20160826_1906... OK
  Applying opal.0024_auto_20160826_1429... OK
  Applying opal.0025_merge... OK
  Applying opal.0026_auto_20161120_2005... OK
  Applying opal.0027_auto_20170114_1302... OK
  Applying opal.0028_auto_20170210_1146... OK
  Applying opal.0029_auto_20170707_1337... OK
  Applying opal.0030_auto_20170719_1016... OK
  Applying opal.0031_auto_20170719_1018... OK
  Applying opal.0032_auto_20171020_1058... OK
  Applying opal.0033_auto_20171205_1553... OK
  Applying opal.0034_auto_20171214_1845... OK
  Applying mynewapp.0001_initial... OK
  Applying reversion.0001_initial... OK
  Applying reversion.0002_auto_20141216_1509... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
Creating superuser
Calling: python mynewapp\manage.py createopalsuperuser --traceback
Calling: git init
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\Scripts\opal-script
.py", line 11, in <module>
    load_entry_point('opal==0.10.0', 'console_scripts', 'opal')()
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\o
pal\core\commandline.py", line 197, in main
    parse_args(sys.argv[1:])
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\o
pal\core\commandline.py", line 192, in parse_args
    args.func(args)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\o
pal\core\commandline.py", line 38, in startproject
    scaffold_utils.start_project(args.name, USERLAND_HERE)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\o
pal\core\scaffold.py", line 255, in start_project
    call(('git', 'init'), cwd=project_dir, stdout=subprocess.PIPE)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\o
pal\core\scaffold.py", line 62, in call
    subprocess.check_call(cmd, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python37\lib\subprocess.py",
 line 323, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python37\lib\subprocess.py",
 line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\user\appdata\local\programs\python\python37\lib\subprocess.py",
 line 743, in __init__
    restore_signals, start_new_session)
  File "c:\users\user\appdata\local\programs\python\python37\lib\subprocess.py",
 line 1087, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by davidmiller** [comment]
Hi @dumodem that's interesting - it's the first time we've seen that!

One of the things that the Opal `startproject` command does is initialise a new git repository in your new project's directory. 

In this case, it seems that it can't find the `git` program on your path.

I think we should probably more gracefully in cases like this though. Having a git repository initialized for you is nice but hardly essential, I reckon we could happily just print a message and continue in case of `FileNotFound` - thoughts @fredkingham @pacharanero ?

**Comment by pacharanero** [comment]
Agreed a Git repo is nice to have but not essential - there are other VCSs and some people do indeed use them. On the other hand you could say 'Opal is opinionated software - we recommend Git and therefore that's what you get by default'

If the `git` command in not found on the $PATH then it should say 

`git was not found on your path. A Git repository has therefore not been initialised`

**Comment by davidmiller** [comment]
@dumodem We've now released Opal 0.10.1 which should have resolved this issue. Thanks for letting us know !
