### ISSUE TITLE
If there is only one list, hide the list switcher

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1513]
Just running through the tutorial. Add a new app. We get an app with a list switch that goes no where.

Shall we just hide it if there is only a single list?

<img width="327" alt="screen shot 2018-04-18 at 18 21 00" src="https://user-images.githubusercontent.com/2175455/38947665-665c5f1c-4335-11e8-82fe-ebaf1c326616.png">

**Comment by pacharanero** [comment]
@fredkingham IIRC you have an Opal app with one PatientList, would you be able to test whether this is fixed by #1517 ?

**Comment by fredkingham** [comment]
@pacharanero  it was just a new opal app. I just ran through the tutorial prior to the last release. I'm afraid I've nuked the app now, can you create a new app and test it? (Sorry!)

**Comment by pacharanero** [comment]
OK I have checked and can confirm that with one patient list in a new Opal app, the ListSwitcher is suppressed using my local branch of Opal `1477-one-spreadsheet-list-to-rule-them-all` via setup.py develop but not suppressed when using Opal v0.10.0.

**Comment by pacharanero** [comment]
closed by #1517
