### ISSUE TITLE
Add angular to the design patterns page and populate it

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1525]
The design patterns page (https://github.com/openhealthcare/opal/blob/v0.11.0/opal/templates/design_patterns.html) is a great asset. At the moment it does not have angular embedded so we cannot show of a lot of our design features. Add this please, then fill in the rest of the form template tags please.

**Comment by davidmiller** [comment]
I think we should kill the page unless / until we can do it well !
