### ISSUE TITLE
'Contributing' link in docs doesn't work

### ISSUE THREAD

**Issue by rossjones** [openhealthcare/opal#1546]
At https://opal.openhealthcare.org.uk/docs/guides/topic-guides/ the link to 'Contributing' raises a 404.

In https://github.com/openhealthcare/opal/tree/v0.11.0/doc/docs/guides the CONTRIBUTING.md file appears to be a symlink - perhaps this is problematic?

**Comment by davidmiller** [comment]
Interesting... it works when I run mkdocs locally 

Looks like @fredkingham last deployed the docs (https://github.com/openhealthcare/opal.openhealthcare.org.uk)

Does it work for you locally @fredkingham ?

**Comment by rossjones** [comment]
I know it's not helpful as I didn't deploy the docs, but it does work for me locally.

**Comment by davidmiller** [comment]
Something about Github pages now lowercases the URL...

see:
https://opal.openhealthcare.org.uk/docs/guides/contributing/ vs https://opal.openhealthcare.org.uk/docs/guides/CONTRIBUTING/

**Comment by fredkingham** [comment]
https://opal.openhealthcare.org.uk/docs/reference/CHANGELOG/ also falls flat on a 404. Is there a reason why we're upper casing? Is it a standard I'm not aware of?

If not I'll lower case'm
