### ISSUE TITLE
Elcid has instances of created/updated by display in the model.

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1574]
It's great, lets have that.

**Comment by fredkingham** [comment]
<img width="926" alt="screen shot 2018-07-20 at 15 05 11" src="https://user-images.githubusercontent.com/2175455/43006725-5c7b8b16-8c2e-11e8-8f3d-7ac9728a6e81.png">

**Comment by davidmiller** [comment]
Merged into v0.13.0
