### ISSUE TITLE
The term active should be dependent on the active category

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1578]
We have a term active which is defined by whether they have any tags.

However some patients have tags and are still inactive.

Please make it dependent on category so that applications can determine for themselves whether an episode should be active or not.

**Comment by davidmiller** [comment]
Setting it this way is almost certainly often wrong:

```python
        if len(tag_names) and not self.active:
            self.active = True
            self.save()
        elif not len(tag_names) and self.active:
            self.active = False
            self.save()
```

If I was going to pick something right now, I suspect the default would be closer to:

```python
@property
def active(self):
    return self.end == None
```

I can see the value of the indirection to category in letting applications override individual episodes... 

Worth checking to see how active is used perhaps.i
