### ISSUE TITLE
Episode Category Inpatient detail template contains models that may not exist in the application

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1600]
Opal, by default, ships with an episode category of Inpatient.

This has the patient detail view detail/inpatient.html.

This declares record panels for models.

These models do not necessarily exist in the application. If they do not exist in the application an error is raised.

On a related note, opal ships with an Outpatient and Liaison category but does not declare detail views for these.

Discussion points.
1. We could declare available categories in the application.
2. `opal startproject` could ship with an inpatient.html.
3. If a detail page is not found we could put in a default template.
4. Detail_template could be a required field for an EpisodeCategory.

Some or all of the above could be implemented.

**Comment by davidmiller** [comment]
If we do anything, I think put the category template in the application.

I think perhaps the whole default category should be in the app.

For now, closing this.
