### ISSUE TITLE
load lookup lists uses the classname.__lower__ in the json dict but looks for a file based on the api name

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1695]
This seems... inconsistent...

**Comment by fredkingham** [comment]
for example the drugfreq.json that comes with opal will never be read as its not the api name. The dictionary it expects to find inside however is class_name.__lower__ which seems wrong...

**Comment by davidmiller** [comment]
I suspect it does load them in b/c `get_api_name` isn't overridden and the default is `__lower__` so, meh - but sure, if you _were_ overriding your lookuplist get_api_name
