### ISSUE TITLE
Adding a user and editing user profile causes an error in the admin

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1712]
Go to the admin, Add a user, click the check box of force password change.

It errors because the user profile has already been created by the signal.

**Comment by Iain-S** [comment]
I can stop this happening by removing `post_save.connect(save_profile, sender=User)` from models.py line 1669.  

Without the post_save call to save_profile, a new UserProfile is still created, though I'm not 100% how.

**Comment by fredkingham** [comment]
👍 yeahI think django admin gets a bit confused with the `post_save.connect` signal. We've got this in https://github.com/openhealthcare/opal/commit/8fe1be83d48d68aecf61879495c910ecaba6f1a8

Which should resolve the issue when we release to pypi (in the next couple of days)

**Comment by fredkingham** [comment]
@Iain-S sorry for the delay this got fixed in the v0.17.0 release that went out today.
