### ISSUE TITLE
emtpy metadata.tags causes "metadata.tags[newTag] is undefined" error

### ISSUE THREAD

**Issue by Iain-S** [openhealthcare/opal#1728]
Hello

With the latest Opal version (v0.15.0), an error occurs when adding a new patient via the /#/list/all_patients page.

### To reproduce
1. Download v0.15.0 from git
1. Start a new project with `opal startproject myNewProj`
1. [optional] Add lookup lists with `load_lookup_lists` and random data with `create_random_data`
1. Start the server and go to 127.0.0.1:8000/#/list/all_patients
1. Click "Add patient"
1. Add any hospital number and a dob
1. Click Save
1. See error in console

### Root cause
On line 276 of patient_list.js, it says:
`metadata.tags[newTag]....`
but newTag is undefined. Ultimately, this is because metadata.tags is empty as can be seen at 127.0.0.1:8000/api/v0.1/.

**Comment by davidmiller** [comment]
Firstly, thanks for a super issue report - it's great.
Secondly, many apologies for our not getting to it sooner.

We've been advising people not to use the javascript Flow functions to manage things like adding / discharging patients for quite some time - you're absolutely right the scaffold app hadn't caught up. 

As of 0.17.x we completely removed the Flow functions and replaced the Add Patient flow in the scaffold app with a simple version of what we do in all of our production applications using Opal.

The code that was previously at L276 has now been deleted so I'm going to close this as no longer relevant - but thanks again for the issue and apologies for nobody picking it up.
