### ISSUE TITLE
Broken link, Opal tutorial page

### ISSUE THREAD

**Issue by aboutmedicine** [openhealthcare/opal#1736]
At the bottom of the tutorial is this text: 

> This is just a glimpse at the full range of functionality that comes with Opal - there is much more to discover in the **Topic Guides**.

Currently directs to https://opal.openhealthcare.org.uk/guides/topic-guides/ which raises a 404. 
Correct link seems to be https://opal.openhealthcare.org.uk/docs/guides/topic-guides/

**Comment by fredkingham** [comment]
This is an excellent spot, thanks for reporting!

We've fixed it in the now live 0.16.0 version of the [page](https://opal.openhealthcare.org.uk/docs/tutorial/)

**Comment by aboutmedicine** [comment]
No worries, thank you for this fantastic repo (and for making it open source of course!)
