### ISSUE TITLE
Move date field on the General Notes and Clinical Advice Modal

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal#174]
When you open these modals the date picker obscures the fields initially.

Could we move this field down one place - so General Notes would be 'Comment' then 'Date' and Clinical Advice would be 'Initials' then 'Date'

**Comment by davidmiller** [comment]
@michaeledwardmarks - is this still a thing?

**Comment by GabPoll** [comment]
i think this has been fixed by having default date as today and then the default cursor position not being the date field. thx.
