### ISSUE TITLE
Reason for Clinical Interaction field no longer brings up a dropdown

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal#177]
Previously on the Clinical Advice modal when you clicked in to the Reason for Clinical Interaction it bought up a drop down of all the auto-complete options.
It was the only field that did so - but I thought worked well, because compared to the other auto-complete lists the entries are not 100% intuitively/obviously named.
So if we could make clicking in to that field bring up the list of options again i think that would be good.
Hope that makes sense

**Comment by davidmiller** [comment]
@michaeledwardmarks - this is now fixed yes?

**Comment by GabPoll** [comment]
yes, thx.
