### ISSUE TITLE
Unable to install Opal. Getting mentioned Error

### ISSUE THREAD

**Issue by RRanjanM** [openhealthcare/opal#1791]
Installing collected packages: rcssmin, rjsmin, django-compressor, opal
  Running setup.py install for rcssmin ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\microsoft visual studio\shared\python37_64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RRanjan\\AppData\\Local\\Temp\\pip-install-h9v22k1s\\rcssmin\\setup.py'"'"'; __file__='"'"'C:\\Users\\RRanjan\\AppData\\Local\\Temp\\pip-install-h9v22k1s\\rcssmin\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\RRanjan\AppData\Local\Temp\pip-record-rl7pldji\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\RRanjan\AppData\Local\Temp\pip-install-h9v22k1s\rcssmin\
    Complete output (10 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying .\rcssmin.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_rcssmin' extension
    b'\\\x00L\x00i\x00b\x00r\x00e\x00O\x00f\x00f\x00i\x00c\x00e\x00 \x00w\x00a\x00s\x00 \x00u\x00n\x00e\x00x\x00p\x00e\x00c\x00t\x00e\x00d\x00 \x00a\x00t\x00 \x00t\x00h\x00i\x00s\x00 \x00t\x00i\x00m\x00e\x00.\x00\r\x00\n\x00'
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files (x86)\microsoft visual studio\shared\python37_64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RRanjan\\AppData\\Local\\Temp\\pip-install-h9v22k1s\\rcssmin\\setup.py'"'"'; __file__='"'"'C:\\Users\\RRanjan\\AppData\\Local\\Temp\\pip-install-h9v22k1s\\rcssmin\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\RRanjan\AppData\Local\Temp\pip-record-rl7pldji\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by davidmiller** [comment]
Hi @RRanjanM 

Rcssmin is a dependency of Opal (Technically of django-compressor 2.2) - it's used to compress the CSS files served by the application.

I'm not sure we can really provide support to help debug compilation of rcssmin on windows unfortunately. 

I would try to reproduce the error by installing rcssmin directly and then asking here: https://github.com/ndparker/rcssmin/

A quick search reveals this ticket: https://github.com/django-compressor/django-compressor/issues/807 
e.g. you may also find that installing rjsmin without c extensions in your virtual environment _before_ you install Opal will help - although this is untested and I don't have access to a Windows machine to try it.

HTH
