### ISSUE TITLE
Tried installing on Fedora 33, Popos 20.10, cannot get past 2nd step

### ISSUE THREAD

**Issue by MrLaaky** [openhealthcare/opal#1960]
On fedora(virtualbox) i get stuck here(1st step ok)
[laaky@localhost ~]$ pip install opal
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: opal in ./Prejemi/somno-master/src/opal (0.12.0)
Requirement already satisfied: ffs>=0.0.8.2 in ./.local/lib/python3.9/site-packages (from opal) (0.0.8.2)
Requirement already satisfied: letter==0.4.1 in ./.local/lib/python3.9/site-packages (from opal) (0.4.1)
Requirement already satisfied: jinja2==2.10 in ./.local/lib/python3.9/site-packages (from opal) (2.10)
Requirement already satisfied: requests==2.18.4 in ./.local/lib/python3.9/site-packages (from opal) (2.18.4)
Requirement already satisfied: django==1.10.8 in ./.local/lib/python3.9/site-packages (from opal) (1.10.8)
Requirement already satisfied: django-reversion==1.10.2 in ./.local/lib/python3.9/site-packages (from opal) (1.10.2)
Requirement already satisfied: django-axes==1.7.0 in ./.local/lib/python3.9/site-packages (from opal) (1.7.0)
Requirement already satisfied: djangorestframework==3.4.7 in ./.local/lib/python3.9/site-packages (from opal) (3.4.7)
Requirement already satisfied: django-compressor==2.2 in ./.local/lib/python3.9/site-packages (from opal) (2.2)
Requirement already satisfied: python-dateutil==2.4.2 in ./.local/lib/python3.9/site-packages (from opal) (2.4.2)
Requirement already satisfied: django-celery==3.2.2 in ./.local/lib/python3.9/site-packages (from opal) (3.2.2)
Requirement already satisfied: celery==3.1.25 in ./.local/lib/python3.9/site-packages (from opal) (3.1.25)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.9/site-packages (from opal) (1.15.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib64/python3.9/site-packages (from jinja2==2.10->opal) (1.1.1)
Requirement already satisfied: idna<2.7,>=2.5 in ./.local/lib/python3.9/site-packages (from requests==2.18.4->opal) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.9/site-packages (from requests==2.18.4->opal) (2020.12.5)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./.local/lib/python3.9/site-packages (from requests==2.18.4->opal) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.9/site-packages (from requests==2.18.4->opal) (3.0.4)
Requirement already satisfied: django-appconf>=1.0 in ./.local/lib/python3.9/site-packages (from django-compressor==2.2->opal) (1.0.4)
Requirement already satisfied: rcssmin==1.0.6 in ./.local/lib/python3.9/site-packages (from django-compressor==2.2->opal) (1.0.6)
Requirement already satisfied: rjsmin==1.0.12 in ./.local/lib/python3.9/site-packages (from django-compressor==2.2->opal) (1.0.12)
Requirement already satisfied: pytz>dev in /usr/lib/python3.9/site-packages (from celery==3.1.25->opal) (2020.1)
Requirement already satisfied: billiard<3.4,>=3.3.0.23 in ./.local/lib/python3.9/site-packages (from celery==3.1.25->opal) (3.3.0.23)
Requirement already satisfied: kombu<3.1,>=3.0.37 in ./.local/lib/python3.9/site-packages (from celery==3.1.25->opal) (3.0.37)
Requirement already satisfied: anyjson>=0.3.3 in ./.local/lib/python3.9/site-packages (from kombu<3.1,>=3.0.37->celery==3.1.25->opal) (0.3.3)
Requirement already satisfied: amqp<2.0,>=1.4.9 in ./.local/lib/python3.9/site-packages (from kombu<3.1,>=3.0.37->celery==3.1.25->opal) (1.4.9)
[laaky@localhost ~]$ opal startproject mynewapp11
Bootstrapping your Opal project...
Creating project dir at /home/laaky/mynewapp11
Creating Database
Calling: python mynewapp11/manage.py makemigrations mynewapp11 --traceback
Traceback (most recent call last):
  File "/home/laaky/mynewapp11/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/laaky/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/laaky/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/laaky/.local/lib/python3.9/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/laaky/.local/lib/python3.9/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/laaky/.local/lib/python3.9/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/laaky/.local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/laaky/.local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
RuntimeError: __class__ not set defining 'AbstractBaseUser' as <class 'django.contrib.auth.base_user.AbstractBaseUser'>. Was __classcell__ propagated to type.__new__?
Failed to run: python mynewapp11/manage.py makemigrations mynewapp11 --traceback
[laaky@localhost ~]$ 

On popos i get stuck here
(newenv) laaky@pop-os:~/newproject/mynewapp/mynewapp$ pip install opal
Requirement already satisfied: opal in /home/laaky/newproject/newenv/src/opal (0.12.0)
Requirement already satisfied: celery==3.1.25 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (3.1.25)
Requirement already satisfied: django-axes==1.7.0 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (1.7.0)
Requirement already satisfied: django-celery==3.2.2 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (3.2.2)
Requirement already satisfied: django-compressor==2.2 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (2.2)
Requirement already satisfied: django-reversion==1.10.2 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (1.10.2)
Requirement already satisfied: django==1.10.8 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (1.10.8)
Requirement already satisfied: djangorestframework==3.4.7 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (3.4.7)
Requirement already satisfied: ffs>=0.0.8.2 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (0.0.8.2)
Requirement already satisfied: jinja2==2.10 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (2.10)
Requirement already satisfied: letter==0.4.1 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (0.4.1)
Requirement already satisfied: python-dateutil==2.4.2 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (2.4.2)
Requirement already satisfied: requests==2.18.4 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (2.18.4)
Requirement already satisfied: six>=1.10.0 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from opal) (1.15.0)
Requirement already satisfied: billiard<3.4,>=3.3.0.23 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from celery==3.1.25->opal) (3.3.0.23)
Requirement already satisfied: pytz>dev in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from celery==3.1.25->opal) (2021.1)
Requirement already satisfied: kombu<3.1,>=3.0.37 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from celery==3.1.25->opal) (3.0.37)
Requirement already satisfied: django-appconf>=1.0 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from django-compressor==2.2->opal) (1.0.4)
Requirement already satisfied: rjsmin==1.0.12 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from django-compressor==2.2->opal) (1.0.12)
Requirement already satisfied: rcssmin==1.0.6 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from django-compressor==2.2->opal) (1.0.6)
Requirement already satisfied: MarkupSafe>=0.23 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from jinja2==2.10->opal) (1.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from requests==2.18.4->opal) (2020.12.5)
Requirement already satisfied: idna<2.7,>=2.5 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from requests==2.18.4->opal) (2.6)
Requirement already satisfied: urllib3(newenv) laaky@pop-os:~/newproject/mynewapp/mynewapp$ <1.23,>=1.21.1 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from requests==2.18.4->opal) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from requests==2.18.4->opal) (3.0.4)
Requirement already satisfied: amqp<2.0,>=1.4.9 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from kombu<3.1,>=3.0.37->celery==3.1.25-(newenv) laaky@pop-os:~/newproject/mynewapp/mynewapp$ >opal) (1.4.9)
Requirement already satisfied: anyjson>=0.3.3 in /home/laaky/newproject/newenv/lib/python3.8/site-packages (from kombu<3.1,>=3.0.37->celery==3.1.25->opal) (0.3.3)

(newenv) laaky@pop-os:~/newproject/mynewapp/mynewapp$ opal startproject mynewapp11
Bootstrapping your Opal project...
Creating project dir at /home/laaky/newproject/mynewapp/mynewapp/mynewapp11
Creating Database
Calling: python mynewapp11/manage.py makemigrations mynewapp11 --traceback
Traceback (most recent call last):
  File "mynewapp11/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/laaky/newproject/newenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/laaky/newproject/newenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/laaky/newproject/newenv/lib/python3.8/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/laaky/newproject/newenv/lib/python3.8/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/laaky/newproject/newenv/lib/python3.8/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/laaky/newproject/newenv/lib/python3.8/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/laaky/newproject/newenv/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
RuntimeError: __class__ not set defining 'AbstractBaseUser' as <class 'django.contrib.auth.base_user.AbstractBaseUser'>. Was __classcell__ propagated to type.__new__?
Failed to run: python mynewapp11/manage.py makemigrations mynewapp11 --traceback

Tried debian, no luck as well. Any pointers? Thank you!

**Comment by davidmiller** [comment]
When you install Opal you're winding up with a version that's very old.

> Requirement already satisfied: opal in /home/laaky/newproject/newenv/src/opal (0.12.0)

At the time of writing the current version on PyPi is 0.20 - I haven't looked it up but I imagine 0.12 didn't support Python 3.8/9. (In fact I imagine it predates them.)

I would try creating a virtual environment that is isolated from any previous package installs, and specifying the version, e.g. `$ pip install opal==0.20.0`

**Comment by MrLaaky** [comment]
Works perfectly! Thank you!

**Comment by davidmiller** [comment]
NP
