### ISSUE TITLE
Extend a core api class

### ISSUE THREAD

**Issue by sushanthko** [openhealthcare/opal#1965]
This might be a very basic question. Could someone please explain the steps to extend a core API class? Eg: `PatientListViewSet`

**Comment by davidmiller** [comment]
Hi @sushanthko 

Slightly unusual question - I'm not sure any Opal app I've ever worked on has actually done that...

Unfortunately, without context about what your trying to do It's impossible to do anything more useful with this question than point you at the class documentation ( https://docs.python.org/3/tutorial/classes.html#inheritance)!

If you could outline what you're trying to achieve we could probably be much more helpful.

**Comment by sushanthko** [comment]
Thanks for the amazing quick reply @davidmiller!

I am trying to build an adaptive user interface for healthcare(long story)  and I ended up with Opal.
I have an app running.
I want to override `retrieve` method from `PatientListViewSet` in core api.
My question basically boils down to where do I place my code.
I tried following the provided `AllPatientsList` class that inherits `PatientList`, but that does not seem to work.

**Comment by davidmiller** [comment]
`I want to override retrieve method from PatientListViewSet in core api.`
Right - this much I figured :) 

But _why_?

High level, how would you alter the method ?

**Comment by sushanthko** [comment]
I am trying to modify the `schema` of the `PatientList`, for each user. It appears that `schema` is applied at class load / app start.
Apologies if these are very basic questions and also for skipping your questions.

**Comment by davidmiller** [comment]
OK - if that's what you're after, then `PatientListViewSet` definitely isn't the thing you're after :) 

`PatientListViewSet` serialises episodes that are on this list, it doesn't handle which data to display - which is the purpose of `schema`. 

If you really need to change schema based on user at runtime for some reason then I would probably override the `template_name`.

You will want to inherit from the 'base' template in opal `templates/patient_lists/layouts/*_base.html` 
In Spreadsheet list you would want to override the block `table`.

I would write a Django inclusion templatetag in the app called something like `dynamic_columns`

A tag that takes context will have both the patient list and the request - hence the user.

You can add a method to your patient list that takes user as an argument and returns columns - see `opal.core.patient_lists.PatientList.schema_to_dicts` for the thing you're effectively replacing with something dynamic. 

Then the inclusion template is the contents of the table block, with your dynamic schema, cast to `opal.core.patient_lists.Column` subclasses run through their `to_dict`. 

HTH

**Comment by sushanthko** [comment]
You are right about `PatientListViewSet`. In my rush, I had not looked at it in depth.
I will try implementing your suggestion. Thanks once again.

**Comment by sushanthko** [comment]
> You can add a method to your patient list that takes user as an argument and returns columns

How would this method be called? How would you pass user as an argument? Could you please explain this with more details?

**Comment by sushanthko** [comment]
@davidmiller I was able to achieve some of what I wanted. Thanks.

Next, I would like to know what is the best way to handle events without breaking the application. For example, when a user clicks save on a form, I want to trigger a custom server side logic (save to db/write to file). The idea is to store user interaction data.

**Comment by davidmiller** [comment]
Really depends what you're trying to track/learn, and hopefully what hypothesis about behaviour you're looking to prove/disprove.

Django Signals https://docs.djangoproject.com/en/3.2/topics/signals/ work
The front end has Angulartics http://angulartics.github.io/  - if you hook it up to a Google Analytics account I think there are a couple of default custom events already, and it'll give you front end page tracking
Django Reversion https://django-reversion.readthedocs.io/en/stable/ also tracks all user edits and 'deletions'

**Comment by davidmiller** [comment]
I'm closing this 'issue' as we're not really e.g. reporting a bug in Opal at all

**Comment by sushanthko** [comment]
I thought I try something out with this [https://opal.openhealthcare.org.uk/docs/guides/forms/#customising-the-angular-controller](url). However, I get `Error: $injector:unpr Unknown Provider`. Any ideas? @davidmiller
