### ISSUE TITLE
Download my logbook button

### ISSUE THREAD

**Issue by drcjar** [openhealthcare/opal#200]
Trainees following the General Internal Medicine Curriculum[1] and several other curricula are required to keep a log book of cases seen e.g [2]

Opal can help with this. Click download my logbook for a csv with the following column headings:

hosp no
patient initials
age
sex
location seen
date seen
diagnosis
notes (this field blank for trainee to populate)

1. http://www.jrcptb.org.uk/trainingandcert/ST3-SpR/Pages/General-Internal-Medicine.aspx
2. http://www.jrcptb.org.uk/trainingandcert/ST3-SpR/Documents/AIM+GIM%20Sample%20Logbook.xls

**Comment by davidmiller** [comment]
This should go in a opal-portfolio plugin. 

Honestly, the mine team should live there as well.

**Comment by davidmiller** [comment]
I'm going to close this here in favour of openhealthcare/opal-ideas#3
