### ISSUE TITLE
Focus in modals is missing

### ISSUE THREAD

**Issue by rossjones** [openhealthcare/opal#207]
Every time a modal is shown the focus is not set, which means having to maneouver the mouse around the screen to select the input.

Please make modals focus the initial input where possible (i.e. Add Patient should focus on the hospital number field so I can just type and press enter.

**Comment by ajmalsha** [comment]
Hi,
 I'm using a conformation popup wit ok and cancel button. When the popup is shown the control is not on it. I need to control this popup using keyboard for example when i press enter the ok should work and when i press Esc the cancel should work. is this possible? If yes how?

Thanks

**Comment by davidmiller** [comment]
Hi @ajmalsha 

If I understand you correctly you're looking for two things:

- Setting focus in modals
- Hooking up keyboard events to actions in modals

Both of these are certainly possible. For keyboards you'll need to register a watch event on the handlers, for focus, you need to make sure you're firing the set focus call at the right time in the Angular digest cycle, which is not the cleanest thing in the world but there are known methods. (As far as I'm aware this is a generic problem with e.g. Angular and modals')

How are you opening your confirmation popup? Do you have an Angular controller already? 
As ever, this is easier with some code to reference than abstractly, but can probably take more of a look later on.

Best David
