### ISSUE TITLE
New loading bar is slow and in a weird place

### ISSUE THREAD

**Issue by andylolz** [openhealthcare/opal#242]
Would be better if the new loading bar:

 * [ ] finished at the same time as the content loads. At the moment it’s slower than the content. To implement this, we need the ability to pass a callback to `ngprogress-lite.done`
 * [ ] appeared just above the newly loaded content. This is fine for routes, but for searching / saving, it would be better if it appeared above the results / in the save modal

**Comment by davidmiller** [comment]
UX tickets that sit stagnant for almost two years become unlikely to be specifically addressed :(

The next step in this is to fix #352 - let's re-visit after that...
