### ISSUE TITLE
Re-formatting dates pre-save causes form fields to look invalid

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#247]
e.g. when saving DOB.

Can we maybe change the format of a copy pre save?

**Comment by fredkingham** [comment]
We are now thinking we should just change the date format to be a singular DD/MM/YYYY format for both the server and the client

**Comment by fredkingham** [comment]
DD/MM/YYYY HH:MM for date time

**Comment by fredkingham** [comment]
so we need to update item.js, filters.js and anywhere else that does moment casting (e.g. patientSummary.js)

**Comment by fredkingham** [comment]
discharge controllers, add episode, admission controllers, setting of defaults, episodes, items
