### ISSUE TITLE
When we go to a list with subteams, create a fast path to skip to the subteam

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#256]
... no need to load all the parent episodes just to redirect.

**Comment by davidmiller** [comment]
Users are complaining about speed.
The practical effect of this would be to make the application feel much snapper.

**Comment by GabPoll** [comment]
at the moment you can already go straight to a sub team - is this an issue in the way elCID loads lists?

**Comment by davidmiller** [comment]
There are times when we don't necessarily do the smartest thing we could do when you navigate lists :(

It means that things are slower and you stay on the loading page for longer than required - we should be able to fix that though !

**Comment by davidmiller** [comment]
Done and ready for deployment...

**Comment by GabPoll** [comment]
is this a backend change?

**Comment by fredkingham** [comment]
nope its all front end efficiencies
