### ISSUE TITLE
The active *row* should be obvious at all times in List view

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#259]
ATM we highlight just the cell...

**Comment by GabPoll** [comment]
+1 :)

But key will be to highlight cell over and above the row as well, to continue permitting keyboard navigation.

**Comment by davidmiller** [comment]
@gabpoll Should now highlight both active cell && row. Do check it out ! :)

**Comment by davidmiller** [comment]
Honestly, this is as obvious as it's going to get for now  !

**Comment by GabPoll** [comment]
fair call. happy to close
