### ISSUE TITLE
As a User I would like a tour of new functionality

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#260]
Perhaps built with Angular Tour ? 

Must store that I've seen a particular step permanently though, so not cookies.
(Most users will use from multiple computers at a given institution, so they'll need their tour progress linked to an account not to account + browser combo !)

http://daftmonk.github.io/angular-tour/#

c.f. 
http://www.useronboard.com/how-slack-onboards-new-users/
http://www.useronboard.com/how-duolingo-onboards-new-users/

**Comment by davidmiller** [comment]
We saw how useful this might be recently when users didn't realise that the functionality to meet their needs did in fact exist, but they simply hadn't found it yet.

**Comment by GabPoll** [comment]
@michaeledwardmarks in case you were wondering, this example was that team tags could be clicked on to bring up team list.

**Comment by davidmiller** [comment]
This is absolutely a useful thing to have, but not really a good Opal ticket for now. This would start as a separate project in the first instance...
