### ISSUE TITLE
Spells and episodes 

### ISSUE THREAD

**Issue by drcjar** [openhealthcare/opal#263]
have we considered this[1] ? helpful?

i.e episode comprises spells

http://www.uhce.ox.ac.uk/hessepho/reports/HESForPhysicians.pdf

**Comment by davidmiller** [comment]
No, because no user need :) 

But... it's a 45 page document... do you have a tl;dr inasmuch as it relates to OPAL beyond the "episodes comprises spells" ?  ;)

**Comment by drcjar** [comment]
all nhs trusts have to submit HES data 
HES data includes the concept of a consultant episode which comprises spells
I suspect it + other things in the 45 page document are somewhat standard across uk health softwares

its something that is likely to become a user need (because of the need for reporting) and for integration purposes that might be better to consider before in advance of it becoming a user need

im not an expert on this :-)

**Comment by davidmiller** [comment]
Figuring out how we export HES data unlikely to be something we focus on short-medium term
