### ISSUE TITLE
Upgrade Libraries

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#270]
- [x] Django (also convert migrations)
- [ ] Angular 
- [ ] Various python dependency libs
- [ ] Various JS dependency libs

**Comment by davidmiller** [comment]
We should also look strongly at consolidating to one Angular - Bootstrap wrapper library as part of this.

**Comment by fredkingham** [comment]
it needs to be noted that because of conflicts in the name space between angular strap and bootstrap ui, I've editted ui-bootstrap-tpls-0.11.0 commenting out the tooltip

**Comment by davidmiller** [comment]
We should indeed upgrade libraries. I'm not sure that this particular now 10 month old ticket is really particularly useful - closing in favour of perhaps looking at it in a designated technical debt sprint post 0.6.
