### ISSUE TITLE
Update search interface

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#285]
- [x] Searching from a single box

> As a user
> I would like to not have to choose what data I am searching by
> So that search works more like things I am used to - like Google.

- [x] Moving the search box: 

> As a User 
> I would like to search from all screens
> So that I can quickly search for patients, saving time and clicks in the interface

- [x] Updating search results
- [x] Search results should be html links
- [x] Don't have Escaping problems
- [x] Search results should respect permissions - e.g. Research patients shouldn't be globally visible

> As a User
> I would like search results to be Patient orientated
> So that they indicate name, MRN, DOB, number and type of episodes

- [x] Paginating search results

> As a User
> I would like search results to be paginated
> So that I can scroll through multiple pages - for instance when I can only remember the first name of a patient with a common name.

**Comment by GabPoll** [comment]
Agree with all that. We may well have elCID tickets on some these.

**Comment by davidmiller** [comment]
https://slack-files.com/files-pri-safe/T03G23JF5-F09NE2YBY/search-and-micro-haem-mockups.pdf?c=1440675775-07efee318a8a7e126f6667d95096ef014b6ce684

**Comment by davidmiller** [comment]
This looks great - it's a massive improvement ! :) 

Few things: 

- [ ] Advanced search displays we've found results at all times
- [ ] Advanced search doesn't paginate
- [ ] Search button is different on Search / Advanced search - it should be the same (@davidmiller increasingly likes the btn-lg buttons FWIW)
- [ ] If there is no DOB we shouldn't show empty brackets

**Comment by davidmiller** [comment]
@fredkingham - did we ever update this to put a search box into the main navbar?

**Comment by davidmiller** [comment]
Can we hide Search for users where userprofile.can_see_pid() == false

**Comment by fredkingham** [comment]
Minor query @davidmiller you mean just having btn-lrg right? the designs had the bigger button for advanced search or have we decided to have the same width of button for both?

**Comment by fredkingham** [comment]
can_see_pid is done on the client side, we should probably do this on the server side in the future, but by the looks of things this might need more thought though (probs don't want to do it in the same way as we're doing it in js)

**Comment by fredkingham** [comment]
now deployed to heroku https://elcid04-test.herokuapp.com/#/list/opat/opat_referrals

**Comment by fredkingham** [comment]
Now deployed to heroku (https://elcid04-test.herokuapp.com/#/list/opat/opat_referrals), let me know what you think @davidmiller @gabpoll @michaelmarks

**Comment by davidmiller** [comment]
@fredkingham Looking good ! 

Few things I've spotted from playing with this: 

- [ ] We should probably kill the query term when we leave search - because it's going to be hard to pass it to other apps, and we should have at least consistent behaviour there

By disabling many of the keyboard shortcuts we've lost some functionality and probably gone too far :)

Shortcuts I think should stay are: 

- [ ] / for search
- [ ] ? for keyboard shortcuts
- [ ] n for new patient
- [ ] up / down for moving between patients.

We should also:

- [ ] Update the keyboard shortcuts modal to reflect the new state of play
- [ ] Add a delete button to modals so that you can delete from list view

**Comment by fredkingham** [comment]
@davidmiller, please take another look, let me know what you think

**Comment by fredkingham** [comment]
btw, this contains the fix to the episode tagging issue
