### ISSUE TITLE
Add utility metadata fields to records

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#292]
We would like the following metadata fields available on the record rather than inferrable through Django Reversion:

- [x] Created (datetime)
- [x] Updated (datetime)
- [x] Created by (FK -> User)
- [x] Updated by (FK -> User)

This should be available for all subrecords, Episode, Patient, Tagging.
We would like to keep the original created/updated when we  clone records.
Cloning records happens when we use the copyToCategory API

**Comment by fredkingham** [comment]
done on elcid04

**Comment by fredkingham** [comment]
@davidmiller one for you to sign off probably https://elcid04-test.herokuapp.com/#/list/microbiology/micro_ortho

**Comment by fredkingham** [comment]
unit tests failing, my bad, fixing

**Comment by fredkingham** [comment]
probably wrongly included in the the 701 branch, I've left  the requirements in there as its a note of the other branches that have also been updated, need to switch before merge.

Sorry there's a lot of stuff on that branch...

**Comment by davidmiller** [comment]
This is super :) 

I think we maybe want these on Episode and Tagging as well and then this can be closed !

**Comment by davidmiller** [comment]
Great stuff !
