### ISSUE TITLE
Patient subrecords are not extracted for all episodes when the patient has multiple admissions

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#296]
e.g. episode id 3114 is patient id 2954 - patient id 2954 has three episodes - only one of which is in demographics.csv

This is caused by the mapping of episode ids to patient ids here: 
https://github.com/openhealthcare/opal/blob/0d7a3a785b36a90806792d651394604d0c29c112/opal/core/search/extract.py#L65 - which is essentially the correct idea but the wrong way round.

/cc @michaeledwardmarks who found this in the wild.

**Comment by davidmiller** [comment]
@fredkingham - I have a feeling this got fixed ?

**Comment by fredkingham** [comment]
I believe so, I think you fixed it!

**Comment by davidmiller** [comment]
Great !
