### ISSUE TITLE
Tagging history should be done better

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#299]
I think looking up via reversion will get really unscalable. My suggestion would be we add a deleted field. Then we never undelete, we create a new model. That way with created/updated timestamps we can have a history of when an episode was tagged, untagged.

(sorry, if we already have a ticket for this, I couldn't find it)

what do you think @davidmiller?

**Comment by davidmiller** [comment]
Broadly I think it's a good idea - we've considered it in the past but never gotten around to it.

Deleted is maybe the wrong fieldname - but we're in danger of bikeshedding here - perhaps archived? 

The key thing is that we'd have to ensure that we converted all of the reversion-based tagging history to the new format - we absolutely can't lose the data.

That said, it's a relatively simple script to write to iterate over all deleted Tagging instances.

**Comment by davidmiller** [comment]
This has been in for at least three versions now - closing this...
