### ISSUE TITLE
As a Doctor I need an active Micro Haem that does not have a list

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#330]
So that I can extract data about MH patients without needing to curate an "active" list.

- [ ] MH patients can be retrieved via advanced search 
- [ ] There is no MH list
- [ ] I should not be able to directly tag a patient to the MH team

**Comment by GabPoll** [comment]
Wow, good spot!

**Comment by GabPoll** [comment]
@fredkingham do you mean patients tagged micro-haem don't show up? If so, that is now fixed and you can close.

If you mean micro haem is not in the drop down for teams in advanced search - that is still the case. We need to be able to do advanced search on micro-haem patients even if no such list exists

**Comment by fredkingham** [comment]
its fixed on elcid04, teams now have a property called visible on list in
the admin view, I think micro haem is marked as inactive but it should be
active but not visibile on list

**Comment by GabPoll** [comment]
and so the fix is to make micro haem visible on the list?

**Comment by fredkingham** [comment]
hopefully the opposite, the fix is that its not "visibile on list" but it is active etc

**Comment by GabPoll** [comment]
Ok. I think i follow. Anyway, the key thing is that micro-haem is an option in the drop down list of teams on advanced search
