### ISSUE TITLE
Generate separate entities from multiple diagnoses entries

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal#35]
At present it is possible to enter multiple diagnoses in a string using commas (very nice by the way) - but if you do this then you can only manipulate that whole block of diagnoses not the individuals diagnoses.

This means 
1) You can only append a comment to that block of diagnoses 
2) Difficult to edit/remove/discard individuals elements of the block

Ideal behavior would be to allow you to enter diagnoses in a string as currently but for each of them to become a separate entity which could have comments added/be deleted manipulated individually.

This links to the points raised in issue #34

**Comment by davidmiller** [comment]
This is now superseded by the discussion in openhealthcare/elcid#312 - we should only have one issue for this ! :)
