### ISSUE TITLE
Extract interface unwieldy with many saved searches

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#351]
The results can get pushed below the fold for users with many saved searches even if they have simple criteria.

I would be highly surprised if many people are using the saved searches functionality and finding that it meets their needs.

Can we ditch it ? @michaeledwardmarks @GabPoll 
We should not let it push results below the fold.

**Comment by GabPoll** [comment]
not too sure what the issue is here, but in general i would be surprised if users are using saved search functionality, given how few advanced search extracts are carried out, and how easy it is to rebuild searches.

**Comment by davidmiller** [comment]
When I was hanging out with some users yesterday, they both had > 7 ! 

They also didn't use them, even when they manually constructed searches that they'd previously saved :(

**Comment by GabPoll** [comment]
Wow! Seems like a feature that wouldn't be missed then!

**Comment by davidmiller** [comment]
Given the work we're going to do early next year on extract/query interfaces, I think this is no longer relevant - yes we should do something about how to save/access/etc saved searches, but it's going to be a very different world !
