### ISSUE TITLE
Ensure that we've forward ported Tags to 0.6

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#445]
- [ ] Fixes to the extract tag names
- [ ] Fixes to the episode list views
- [ ] Updates to documentation
- [ ] The 0.6.0 should be mergable with master (Post 0.5.5 release)

**Comment by davidmiller** [comment]
@fredkingham You looked at this and it's done?

**Comment by fredkingham** [comment]
yeah, I think its covered by the commit
https://github.com/openhealthcare/opal/commit/5cbffefb94d440ed9558714164cea9c8749bc60d

**Comment by davidmiller** [comment]
Great stuff !
