### ISSUE TITLE
More realistic Create Random Data

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#504]
For some subrecords Creating random data causes a particularly high degree of cognitive dissonance - for example Investigations are never realistic. 

We would appreciate the ability to define a hook somewhere for creating randomised instances of a particular subrecord so that we can implement this on a case by case basis to override the default.

**Comment by fredkingham** [comment]
see openhealthcare/elcid#1091 for an example of data integrity that needs to be improved

**Comment by davidmiller** [comment]
I'm going to close this here - while it would be nice to have, I think we have more pressing concerns - let's do it in an app / plugin then move it into Opal itself...
