### ISSUE TITLE
Saving update to dict seems to save the episode multiple times

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#532]
the saving signal fires multiple times on creating an asset.

It could just be that django saves both sides of a foreign key relationship on every subrecord save but this seems costly

**Comment by davidmiller** [comment]
@fredkingham is this still true ?

It's not the `dispatch_uid` thing ? 

https://docs.djangoproject.com/en/1.10/topics/signals/#preventing-duplicate-signals

**Comment by davidmiller** [comment]
@fredkingham is this still the case ?

**Comment by fredkingham** [comment]
tested this on the latest version and it didn't happen
