### ISSUE TITLE
the initial log in page should remember your previous list site

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#599]

**Comment by fredkingham** [comment]
I'm bumping this for the time being, as cookies by default expire when you close the browser. It looks like angular 1.4 gives us an expiration date on the cookies which would be a better use but requires an upgrade to 1.4 (or 1.5!), which we don't want to do this close to a release

**Comment by davidmiller** [comment]
https://github.com/openhealthcare/elcid/issues/743 seems particularly relevant here

**Comment by davidmiller** [comment]
This has been implemented now with https://github.com/openhealthcare/opal/commit/3c3b6017ed1eb1d33f4cb69368eef92fb14d2a36
