### ISSUE TITLE
bulk update doesn't update tagging

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#667]
we need to write bulk update for tagging, at the moment its special case removed

**Comment by davidmiller** [comment]
Moreover, if you save tagging via /api/v0.1/tagging/10/ it behaves differently to /api/v0.1/episode/10/ with tagging in the episode dict.

These should probably all do the same thing.

**Comment by davidmiller** [comment]
Moreover if you save tagging via /api/v0.1/tagging/10/ with `{'inpatient': True, 'id': 1}` we set tag names to ['inpatient', 'id'].

**Comment by davidmiller** [comment]
Closed in https://github.com/openhealthcare/opal/pull/1336
