### ISSUE TITLE
Reference data

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#672]
- [x] load lookup lists should be hierachical
- [ ] lookup lists should be taggable
- [ ] lookup lists should also have a one to many link to external identifiers (e.g. snomed ct)
- [ ] look up lists should be versioned

**Comment by davidmiller** [comment]
I'm going to close this.... not that I don't think that 'taggable' or external ids or versioning is a bad thing, but we're surely going to re-approach the architecture and design anyway when we do get to it.
