### ISSUE TITLE
Form helpers should use Verbose names in labels

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#699]
This is the Django way of setting display names for things - let's allow ourselves to do that.

https://docs.djangoproject.com/en/1.9/topics/db/models/#verbose-field-names

**Comment by davidmiller** [comment]
@fredkingham Have we now done this ? At least for when you use the `field= ` API?

**Comment by fredkingham** [comment]
Yep, job done

**Comment by davidmiller** [comment]
Great!
