### ISSUE TITLE
Be nice to users when they exceed the maximum value for a charfield

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#738]
Currently a value that exceeds the max_length for a charfield will result in a 500 error from the server and a `DataError: value too long for type character varying(255)`.

We need to 
- [ ] Not 500
- [ ] Return an appropriate error code and error messages
- [ ] Allow that error message to flow forwards to the user if they post a field that is too long
- [ ] Look at validation before it happens - can we set the max_length into the `{% input ` we're generating?

**Comment by GabPoll** [comment]
i love the title of the issue
