### ISSUE TITLE
Handling required fields

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#744]
Some fields are required - see Demographics Hospital number in elCID. 

The current behaviour for a user attempting to create an episode without a hospital number is to  raise `IntegrityError null value in column` - which is obviously silly.

When we have required fields at the _database_ level: 
- The forms should reflect the fact that the thing is truly required
- The API should return an invalid style error message if the user attempts to post without it.

**Comment by fredkingham** [comment]
the api will 500 which is not great, however https://github.com/openhealthcare/opal/blob/v0.18.2/opal/templatetags/forms.py
infers required fields from the database (or you can add `required=True` to the template tag.

Form validation and errors are displayed on the client and the form cannot be submitted until they are fixed.
