### ISSUE TITLE
UX for adding names

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#752]
Now that we have complex, multi-part name fields, it might be nice to provide a way to enable data entry of names that isn't every-field-on-a-new-line ?

Perhaps an inline Title dropdown, first, last as a template tag ?

@fredkingham y/n ? Thoughts?

**Comment by fredkingham** [comment]
yep, sounds good

**Comment by davidmiller** [comment]
We're going to steer clear of steering people on this for now I suspect. Not likely to look at it soon.
