### ISSUE TITLE
Do we still need Modal Size now that everything is large?

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#850]
We currently have it as a Subrecord option, passed through in /records/, and interrogated in Item() and recordEditor().

Perhaps just remove, and while we're at it, set as a global configuration option so that we don't have to pass it in everywhere?

**Comment by GabPoll** [comment]
Current modal sizes seem fine to me. Not sure if i'm commenting on correct issue though!

**Comment by davidmiller** [comment]
@GabPoll yep, I reckon the current modal sizes are fine - this one more about cleaning up the underlying code - once upon a time only some of the modals were wide (mostly because of the allergy sidebar - I think that's no longer required now so we can remove it... 

As a user you should notice no difference whatsoever !
