### ISSUE TITLE
Highlight Antibiotics that are still active to improve readability

### ISSUE THREAD

**Issue by wai2k** [openhealthcare/opal#911]
![image](https://cloud.githubusercontent.com/assets/1630790/20817458/c074ea5c-b81f-11e6-87e5-d437f7dedde1.png)

At the moment it can be difficult at a glance to see which antibiotic the patient is still on. Can the active ie. No end date Antibiotics be made bold or the discontinued one made slightly greyer?

In this example, it can be easy to miss that the patient is still on Ambisome.

**Comment by davidmiller** [comment]
That's very true actually - I was thinking this the other day...

I have a sense that separating into current treatment and pat treatment
might help - but that could make it hard to understand the progression.

Suspect there's something you can do with a timeline type display but I've
not say down to think about it properly...

Have you seen this done particularly well anywhere?

**Comment by davidmiller** [comment]
Three options mentioned here would look something like this: 

![abx bold](https://cloud.githubusercontent.com/assets/17229/20842164/7ff7d694-b8ae-11e6-9dbf-f5387c2012a6.png)
![abx grey](https://cloud.githubusercontent.com/assets/17229/20842165/7ff96004-b8ae-11e6-9435-4a6febcec55d.png)
![abx split](https://cloud.githubusercontent.com/assets/17229/20842166/8012742c-b8ae-11e6-963b-46cf6e1547c0.png)

Any preferences ? 
@GabPoll @michaeledwardmarks @drcjar perhaps?

**Comment by GabPoll** [comment]
Ummm - i think i replied to this yesterday but didn't come through.

I would prefer one that is a composite of all those. I would have one big list, but active Abx at the top in bold. Also strong proponent of tabulating (no need to show table borders), so that can clearly see the current antibiotics that are lacking end dates

**Comment by JMathiszig-Lee** [comment]
This is old but i think the grey version is the best. It both makes it clear what antibiotics are current and in what order they were started

**Comment by tom-parks** [comment]
As discussed I prefer the spilt view with current and historic separate. It would make sense to replicate this on the lists.

**Comment by drcjar** [comment]
I think this is tricky. I like grey or split.

With antibiotics I want to see what's on now because a) I want to know if I can narrow or stop it  b) it's not working and I want to try something else. I think this is helped by split view. 

Other times I want to review the chronology of events e.g LFTs have gone off on todays bloods, were ok 3/7 ago, what antibiotics changed?

It'd be nice to a/b test and/or let user set a preferred view.

**Comment by tom-parks** [comment]
For your second requirement it would be really cool if we could pull up a little figure charting use over time i.e. blocks for each drug

**Comment by fredkingham** [comment]
@wai2k @tom-parks @drcjar @JMathiszig-Lee @GabPoll hi guys, sorry this took so long.

Please review http://elcid0624.herokuapp.com/#/patient/1/1

we've ended up going with the greying out as the simplest implementation at the end. Do people think this is apparent/obvious.

Note if a drug finishes today, its greyed out, but not if its in the future. Is this behaviour ok?

thanks

**Comment by tom-parks** [comment]
Hi Fred,

Can you remind me of the heroukapp login?

Thanks,

Tom


On 19 Jan 2017, at 12:58, Fred <notifications@github.com<mailto:notifications@github.com>> wrote:


@wai2k<https://github.com/wai2k> @tom-parks<https://github.com/tom-parks> @drcjar<https://github.com/drcjar> @JMathiszig-Lee<https://github.com/JMathiszig-Lee> @GabPoll<https://github.com/GabPoll> hi guys, sorry this took so long.

Please review http://elcid0624.herokuapp.com/#/patient/1/1

we've ended up going with the greying out as the simplest implementation at the end. Do people think this is apparent/obvious.

Note if a drug finishes today, its greyed out, but not if its in the future. Is this behaviour ok?

thanks

**Comment by fredkingham** [comment]
@tom-parks 
username: super
password: super1

**Comment by tom-parks** [comment]
@fredkingham @davidmiller This works for me and presumably could be updated in the future. I guess the thing I'd like to see most would be a list sorted into current and past.

**Comment by fredkingham** [comment]
@tom-parks do we always want to see a split between past and present, do we not sometimes want ordered by start date?

**Comment by tom-parks** [comment]
@fredkingham @davidmiller Regarding the antibiotic finish date I'd suggest the antibiotic goes grey on the day after it completes. This seems to make more sense to me from the point-of-view of drug reactions etc.

**Comment by tom-parks** [comment]
@fredkingham @davidmiller Clearly the system was built originally to order by start date originally and there may have been logic behind that. But for me the order of questions in my head is i) what's the patient taking now ii) what's the timing of those. So for me if would be ideal to sort by current/past then start date.

**Comment by fredkingham** [comment]
@tom-parks good call on not greying out the same day, I think we're going to push any reordering for the time being, as its non-trivial (because the panel appears in quite a lo of places). 

We can look at doing that in the future maybe

**Comment by fredkingham** [comment]
@wai2k @drcjar  @JMathiszig-Lee @GabPoll 

Any other feedback on this guys, @tom-parks and I are planning to release this on Sunday if no one has any issues

**Comment by fredkingham** [comment]
@wai2k @drcjar @GabPoll

btw, after a slight delay, we deployed this last night

**Comment by GabPoll** [comment]
Great news. Can i have a heroku link to see the new version please?

________________________________

**Comment by fredkingham** [comment]
yessiree http://elcid0624.herokuapp.com/#/list/infectious_diseases-id_inpatients
